import test from 'node:test';
import assert from 'node:assert/strict';
import {consumeOaCallback} from '../oa.mjs';
function consume(href){let cleaned;const result=consumeOaCallback({href},{state:{keep:true},replaceState(state,_,url){assert.deepEqual(state,{keep:true});cleaned=url;}});return {result,cleaned};}
test('OA ticket精确解码并清理地址，保留其他业务参数',()=>{const {result,cleaned}=consume('https://example.test/mobile/?ticket=a%2Bb%26c%3D%23&tab=todo#detail');assert.equal(result.ticket,'a+b&c=#');assert.equal(cleaned,'/mobile/?tab=todo#detail');});
test('兼容oaToken以及hash路由回调',()=>{assert.equal(consume('https://example.test/mobile/?oaToken=one').result.ticket,'one');const {result,cleaned}=consume('https://example.test/mobile/#/callback?ticket=one&tab=todo');assert.equal(result.ticket,'one');assert.equal(cleaned,'/mobile/#/callback?tab=todo');});
test('空票、重复参数、别名冲突均清理并拒绝',()=>{for(const query of ['ticket=','ticket=a&ticket=b','ticket=a&oaToken=b','ticket='+'x'.repeat(4097)]){const {result,cleaned}=consume('https://example.test/mobile/?'+query);assert.equal(result.present,true);assert.ok(result.error);assert.equal(result.ticket,undefined);assert.equal(cleaned,'/mobile/');}assert.ok(consume('https://example.test/mobile/?ticket=a#/callback?ticket=b').result.error);});
test('普通name参数和包含ticket字样的业务参数不视作身份',()=>{const {result,cleaned}=consume('https://example.test/mobile/?name=admin&redirect=ticket');assert.equal(result.present,false);assert.equal(cleaned,undefined);});
import {restoreOaToken} from '../oa.mjs';
test('中转系统token清理后独立于ticket消费，保留业务参数',()=>{const {result,cleaned}=consume('https://example.test/mobile/?token=ccr%2Btoken&source=oa&tab=todo');assert.deepEqual(result,{present:true,token:'ccr+token'});assert.equal(cleaned,'/mobile/?tab=todo');assert.equal(consume('https://example.test/mobile/#/callback?token=abc&source=oa').result.token,'abc');});
test('系统token重复、混用票据、错误渠道及非法格式均清理并拒绝',()=>{for(const query of ['token=','token=a&ticket=b','token=a&oaToken=b','token=a&token=b','token=a&source=youdu','token=a&source=oa&source=oa','token=a%0Ab']){const {result,cleaned}=consume('https://example.test/mobile/?'+query);assert.ok(result.error);assert.doesNotMatch(cleaned,/token=|ticket=|oaToken=/);}});
test('系统token先替换旧会话，仅调用session校验，权限拒绝后清除',async()=>{let value='old',source;const session={clear(){value=null},set(t,s){value=t;source=s}};const profile={userName:'fixture'};assert.equal(await restoreOaToken('new',{session,request:async path=>{assert.equal(path,'/session');assert.equal(value,'new');return profile}}),profile);assert.equal(source,'oa');for(const code of [401,403,0]){await assert.rejects(restoreOaToken('bad',{session,request:async()=>{throw Object.assign(Error('denied'),{code})}}));assert.equal(value,null);}});
