import test from 'node:test';import assert from 'node:assert/strict';
import {qualitySummary} from '../quality.mjs';import {clampZoom,touchDistance,zoomAnchor} from '../preview-zoom.mjs';
test('多条 PASS 空说明汇总为通过，不能成为黄色异常',()=>{const result=qualitySummary(Array.from({length:10},()=>({ruleLevel:'PASS',message:null})));assert.equal(result.passed,10);assert.deepEqual(result.issues,[]);});
test('警告与阻断保留，缺少说明使用规则码，未知级别不能按通过处理',()=>{const result=qualitySummary([{ruleLevel:'PASS'},{ruleLevel:'WARN',message:'日期较旧'},{ruleLevel:'BLOCK',ruleCode:'CUSTOMER_REQUIRED'},{ruleLevel:'OTHER'}]);assert.equal(result.passed,1);assert.deepEqual(result.issues.map(r=>r.label),['需关注','未通过','待核实']);assert.equal(result.issues[1].message,'CUSTOMER_REQUIRED');});
test('PDF 双指距离控制缩放，限制 100%-300%，保持触点位置',()=>{assert.equal(touchDistance([{clientX:0,clientY:0},{clientX:30,clientY:40}]),50);assert.equal(clampZoom(2),2);assert.equal(clampZoom(9),3);assert.equal(clampZoom(.5),1);assert.equal(clampZoom(NaN),1);assert.equal(zoomAnchor(50,100,1,2),200);assert.equal(zoomAnchor(0,100,2,1),0);});
import {attachmentKind,previewType} from '../files.mjs';
test('附件图标识别大小写图片和 PDF，未知文件兜底且不改变内容校验',()=>{for(const name of ['照片.JPG','照片.jpeg','照片.PNG','照片.webp'])assert.equal(attachmentKind(name),'image');assert.equal(attachmentKind('材料.PDF'),'pdf');assert.equal(attachmentKind('材料.docx'),'file');assert.equal(attachmentKind(undefined),'file');assert.equal(previewType(new TextEncoder().encode('<html>fake.pdf')) ,null);});
import {resetDetailScroll} from '../detail-scroll.mjs';
test('深滚动切换标签后定位内容起点，短内容只补齐视口高度',()=>{let result;const scroll={scrollTop:950,clientHeight:720,getBoundingClientRect:()=>({top:52}),scrollTo:value=>result=value};const panel={style:{},closest:()=>scroll,getBoundingClientRect:()=>({top:-550})};resetDetailScroll(panel,{offsetHeight:50});assert.equal(result.top,298);assert.equal(result.behavior,'instant');assert.equal(panel.style.minHeight,'670px');resetDetailScroll(null,null);});
