-- ============================================================
-- 客户贡献度与利率决策系统 · 核心业务表(ccr_*)
-- 依据:设计文档V1.0 §9.2、附录A.1/A.2/A.3
-- 公共字段(附录A.1): id雪花主键/tenant_id/business_no/org_id/status/version_no/
--   create_dept/create_by/create_time/update_by/update_time/del_flag
-- 金额 DECIMAL(20,4)(万元);利率 DECIMAL(9,6)(百分值)
-- 审批/投票/决议/快照表逻辑上禁止物理删除(代码层控制)
-- ============================================================

USE `ccr_rate`;

-- ---------- 申请主单 ----------
CREATE TABLE IF NOT EXISTS `ccr_application` (
  `id`                  BIGINT       NOT NULL COMMENT '雪花主键',
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000' COMMENT '租户标识',
  `business_no`         VARCHAR(64)  NOT NULL COMMENT '表内唯一业务编号',
  `org_id`              BIGINT       NOT NULL COMMENT '数据归属机构',
  `status`              VARCHAR(32)  NOT NULL COMMENT 'DRAFT/SUBMITTING/PROCESSING/PARTIAL_APPROVED/APPROVED/REJECTED/CLOSED',
  `version_no`          INT          NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
  `create_dept`         BIGINT       NULL COMMENT '创建部门',
  `create_by`           BIGINT       NOT NULL COMMENT '创建人',
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by`           BIGINT       NULL COMMENT '最后修改人',
  `update_time`         DATETIME     NULL COMMENT '最后修改时间',
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0' COMMENT '逻辑删除标识',
  `application_no`      VARCHAR(64)  NOT NULL COMMENT '申请号(唯一)',
  `business_type`       VARCHAR(16)  NOT NULL COMMENT 'LOAN贷款/DEPOSIT存款',
  `customer_scope`      VARCHAR(16)  NOT NULL COMMENT 'INDIVIDUAL/CORPORATE_SINGLE/GROUP',
  `customer_no`         VARCHAR(64)  NULL COMMENT '个人或企业单户客户号(集团场景为空)',
  `group_no`            VARCHAR(64)  NULL COMMENT '集团客户编号(集团场景必填)',
  `applicant_user_id`   BIGINT       NOT NULL COMMENT '客户经理',
  `applicant_org_id`    BIGINT       NOT NULL COMMENT '提交机构',
  `source_application_id` BIGINT     NULL COMMENT '关联重提的原申请',
  `snapshot_bundle_id`  BIGINT       NULL COMMENT '提交成功绑定不可变快照包',
  `rule_set_version_id` BIGINT       NULL COMMENT '冻结利率规则集版本',
  `lpr_version_id`      BIGINT       NULL COMMENT '冻结LPR版本',
  `flow_definition_version` VARCHAR(64) NULL COMMENT '冻结流程定义版本',
  `submit_time`         DATETIME     NULL COMMENT '最终提交时间',
  `final_time`          DATETIME     NULL COMMENT '主申请终态时间',
  `application_remark`  VARCHAR(1000) NULL COMMENT '客户经理备注(手工描述,展示在审批界面)',
  `route_as_of_date`    DATETIME     NULL COMMENT '提交冻结的路由/LPR生效日期(§8.4,在途沿用)',
  `data_baseline_json`  JSON         NULL COMMENT '草稿创建/上次预览时各数仓数据集数据日期基线(§7.1步骤9比对)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_application_no` (`application_no`),
  KEY `idx_app_org_status` (`applicant_org_id`,`status`),
  KEY `idx_app_applicant` (`applicant_user_id`,`status`),
  KEY `idx_app_create` (`create_time`),
  KEY `idx_app_customer` (`customer_no`),
  KEY `idx_app_group` (`group_no`)
) ENGINE=InnoDB COMMENT='ccr_application 利率申请主单';

-- ---------- 集团申请涉及成员 ----------
CREATE TABLE IF NOT EXISTS `ccr_application_member` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `member_customer_no`  VARCHAR(64)  NOT NULL COMMENT '本次涉及成员客户号',
  `member_limit_ref`    VARCHAR(64)  NULL COMMENT '数仓成员额度来源主键',
  `member_limit_amount` DECIMAL(20,4) NULL COMMENT '提交时成员额度快照值',
  `request_amount`      DECIMAL(20,4) NOT NULL COMMENT '本次申请涉及金额',
  `currency`            VARCHAR(8)   NOT NULL DEFAULT 'CNY' COMMENT 'ISO币种编码',
  `member_role`         VARCHAR(32)  NULL COMMENT '冻结成员角色(核心/一般)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_member` (`application_id`,`member_customer_no`),
  KEY `idx_member_no` (`member_customer_no`)
) ENGINE=InnoDB COMMENT='ccr_application_member 集团申请涉及成员';

-- ---------- 利率定价分项 ----------
CREATE TABLE IF NOT EXISTS `ccr_pricing_item` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL COMMENT 'DRAFT/ROUTING/LEVEL_APPROVAL/VOTING/PRESIDENT_DECISION/APPROVED/REJECTED/VETOED/SUPERSEDED/CLOSED',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '所属申请',
  `pricing_item_no`     VARCHAR(64)  NOT NULL COMMENT '定价分项编号(唯一)',
  `pricing_customer_no` VARCHAR(64)  NOT NULL COMMENT '实际定价客户号(集团场景为成员)',
  `member_customer_no`  VARCHAR(64)  NULL COMMENT '集团成员客户号（集团场景必填）',
  `pricing_carrier_type` VARCHAR(24) NOT NULL COMMENT 'LOAN_CONTRACT/DEPOSIT_ACCOUNT',
  `credit_tranche_ref`  VARCHAR(64)  NULL COMMENT '用信或担保分项来源主键',
  `product_code`        VARCHAR(32)  NOT NULL COMMENT '产品编码',
  `guarantee_package_id` BIGINT      NULL COMMENT '冻结担保组合',
  `term_value`          INT          NOT NULL COMMENT '期限数值',
  `term_unit`           VARCHAR(8)   NOT NULL COMMENT '日/月/年',
  `pricing_amount`      DECIMAL(20,4) NOT NULL COMMENT '分项定价金额(万元)',
  `currency`            VARCHAR(8)   NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `original_rate`       DECIMAL(9,6) NULL COMMENT '原执行利率(新增业务可为空)',
  `requested_rate`      DECIMAL(9,6) NOT NULL COMMENT '客户经理申请利率',
  `current_approval_rate` DECIMAL(9,6) NOT NULL COMMENT '当前审批利率(随调价更新)',
  `final_rate`          DECIMAL(9,6) NULL COMMENT '最终决议利率',
  `rate_direction`      VARCHAR(16)  NOT NULL COMMENT 'LOWER_BETTER/HIGHER_BETTER',
  `route_code`          VARCHAR(64)  NULL COMMENT '计算得到路由编码',
  `flow_instance_id`    VARCHAR(64)  NULL COMMENT '工作流实例标识',
  `current_node_code`   VARCHAR(64)  NULL COMMENT '当前节点编码',
  `start_node_code`     VARCHAR(64)  NULL COMMENT '审批链首节点编码(提交路由后冻结,§8.6;贷款/存款恒为BRANCH_MANAGER)',
  `boundary_rate`       DECIMAL(9,6) NULL COMMENT '终审节点边界利率(矩阵∩产品硬边界交集,提交路由后冻结,§8.6)',
  `matched_matrix_no`   VARCHAR(64)  NULL COMMENT '命中的权限矩阵行编号(提交路由后冻结,审计溯源,§8.6)',
  `final_reason`        VARCHAR(1000) NULL COMMENT '最终否决或一票否决原因',
  `source_pricing_item_id` BIGINT    NULL COMMENT '关联重提来源分项(§7.6)',
  `inherit_flag`        CHAR(1)      NOT NULL DEFAULT 'N' COMMENT '是否沿用原决议Y/N(D18b:已批准分项连同最终利率与快照保留,不重新审批)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pricing_item_no` (`pricing_item_no`),
  KEY `idx_pricing_app_status` (`application_id`,`status`),
  KEY `idx_pricing_node_status` (`current_node_code`,`status`),
  KEY `idx_pricing_customer` (`pricing_customer_no`,`create_time`),
  KEY `idx_pricing_member` (`member_customer_no`),
  KEY `idx_pricing_source` (`source_pricing_item_id`)
) ENGINE=InnoDB COMMENT='ccr_pricing_item 利率定价分项(审批原子单位)';

-- ---------- 分项与贷款合同关系 ----------
CREATE TABLE IF NOT EXISTS `ccr_pricing_item_contract_rel` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项主键',
  `contract_business_key` VARCHAR(64) NOT NULL COMMENT '合同业务标识(现有合同号或拟签合同标识)',
  `loan_contract_no`    VARCHAR(64)  NULL COMMENT '回填的正式合同号',
  `contract_snapshot_id` BIGINT      NULL COMMENT '冻结合同快照记录id',
  `planned_contract_flag` CHAR(1)    NOT NULL DEFAULT 'N' COMMENT '是否拟签合同Y/N',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_contract` (`application_id`,`contract_business_key`,`del_flag`),
  KEY `idx_pricing_item` (`pricing_item_id`),
  KEY `idx_contract_no` (`loan_contract_no`)
) ENGINE=InnoDB COMMENT='ccr_pricing_item_contract_rel 分项与贷款合同关系(唯一键含del_flag,失效后可重绑;有效记录唯一由服务层保证)';

-- ---------- 分项与存款账户关系 ----------
CREATE TABLE IF NOT EXISTS `ccr_pricing_item_deposit_rel` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项主键',
  `deposit_account_no_cipher` VARCHAR(512) NULL COMMENT '存款账号密文(拟开户可空)',
  `deposit_account_hash` CHAR(64)    NULL COMMENT '存款账号查询哈希',
  `account_snapshot_id` BIGINT       NULL COMMENT '冻结账户快照记录id',
  `planned_account_flag` CHAR(1)     NOT NULL DEFAULT 'N' COMMENT '是否拟开户方案Y/N',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_account` (`application_id`,`deposit_account_hash`,`del_flag`),
  KEY `idx_pricing_item` (`pricing_item_id`)
) ENGINE=InnoDB COMMENT='ccr_pricing_item_deposit_rel 分项与存款账户关系(唯一键含del_flag,失效后可重绑;有效记录唯一由服务层保证)';

-- ---------- 担保组合 ----------
CREATE TABLE IF NOT EXISTS `ccr_guarantee_package` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `package_no`          VARCHAR(64)  NOT NULL COMMENT '担保组合编号',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项(唯一,提交后不可修改)',
  `package_version`     INT          NOT NULL DEFAULT 1 COMMENT '担保组合版本',
  `main_guarantee_type` VARCHAR(32)  NOT NULL COMMENT '担保主类型',
  `ext_json`            JSON         NULL COMMENT '扩展属性',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_package_no` (`package_no`),
  UNIQUE KEY `uk_package_pricing_item` (`pricing_item_id`)
) ENGINE=InnoDB COMMENT='ccr_guarantee_package 担保组合';

-- ---------- 担保措施 ----------
CREATE TABLE IF NOT EXISTS `ccr_guarantee_measure` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `package_id`          BIGINT       NOT NULL COMMENT '担保组合主键',
  `measure_no`          VARCHAR(64)  NOT NULL COMMENT '担保措施编号(唯一)',
  `measure_type`        VARCHAR(32)  NOT NULL COMMENT 'CREDIT/GUARANTEE/MORTGAGE/PLEDGE/BILL_MARGIN/CREDIT_MARGIN/CERTIFICATE_DEPOSIT',
  `guarantor_customer_no` VARCHAR(64) NULL COMMENT '担保人客户号(保证)',
  `collateral_no`       VARCHAR(64)  NULL COMMENT '抵质押物编号',
  `guarantee_amount`    DECIMAL(20,4) NOT NULL COMMENT '担保金额(万元)',
  `currency`            VARCHAR(8)   NOT NULL DEFAULT 'CNY',
  `ext_json`            JSON         NULL COMMENT '扩展属性',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_measure_no` (`measure_no`),
  KEY `idx_measure_package` (`package_id`)
) ENGINE=InnoDB COMMENT='ccr_guarantee_measure 担保措施';

-- ---------- 借据与担保措施多对多 ----------
CREATE TABLE IF NOT EXISTS `ccr_note_guarantee_rel` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `loan_note_no`        VARCHAR(64)  NOT NULL COMMENT '借据号',
  `measure_id`          BIGINT       NOT NULL COMMENT '担保措施主键',
  `covered_amount`      DECIMAL(20,4) NOT NULL COMMENT '覆盖金额(万元)',
  `currency`            VARCHAR(8)   NOT NULL DEFAULT 'CNY',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_note_measure` (`loan_note_no`,`measure_id`)
) ENGINE=InnoDB COMMENT='ccr_note_guarantee_rel 借据与担保措施多对多';

-- ---------- 原申请与重提关系 ----------
CREATE TABLE IF NOT EXISTS `ccr_application_relation` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `source_application_id` BIGINT     NOT NULL COMMENT '原申请主键',
  `target_application_id` BIGINT     NOT NULL COMMENT '重提申请主键',
  `relation_type`       VARCHAR(16)  NOT NULL COMMENT 'REAPPLY重提/REPLACE替换',
  `source_pricing_item_id` BIGINT    NULL COMMENT '原定价分项主键',
  `target_pricing_item_id` BIGINT    NULL COMMENT '重提定价分项主键',
  `inherit_flag`        CHAR(1)      NOT NULL DEFAULT 'N' COMMENT '是否沿用原决议Y/N',
  `remark`              VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rel` (`source_application_id`,`target_application_id`),
  KEY `idx_target` (`target_application_id`)
) ENGINE=InnoDB COMMENT='ccr_application_relation 原申请与重提关系';

-- ---------- 节点调价记录 ----------
CREATE TABLE IF NOT EXISTS `ccr_rate_adjustment` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项主键',
  `node_code`           VARCHAR(64)  NOT NULL COMMENT '审批节点编码',
  `before_rate`         DECIMAL(9,6) NOT NULL COMMENT '调整前利率',
  `after_rate`          DECIMAL(9,6) NOT NULL COMMENT '调整后利率',
  `boundary_min_rate`   DECIMAL(9,6) NULL COMMENT '本节点权限下界',
  `boundary_max_rate`   DECIMAL(9,6) NULL COMMENT '本节点权限上界',
  `adjust_reason`       VARCHAR(1000) NULL COMMENT '调整理由',
  `operator_id`         BIGINT       NOT NULL COMMENT '操作人',
  `operation_channel`   VARCHAR(16)  NOT NULL COMMENT 'PC/MOBILE',
  `device_id`           VARCHAR(64)  NULL COMMENT '设备标识',
  `operation_time`      DATETIME     NOT NULL COMMENT '操作时间',
  PRIMARY KEY (`id`),
  KEY `idx_adjust_pricing` (`pricing_item_id`),
  KEY `idx_adjust_operator` (`operator_id`,`operation_time`)
) ENGINE=InnoDB COMMENT='ccr_rate_adjustment 节点调价记录(全程审计)';

-- ---------- 审批业务轨迹 ----------
CREATE TABLE IF NOT EXISTS `ccr_approval_action` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项主键',
  `task_id`             VARCHAR(64)  NULL COMMENT '工作流任务标识',
  `action_type`         VARCHAR(32)  NOT NULL COMMENT 'APPROVE/REJECT/PRESIDENT_APPROVE/VETO',
  `node_code`           VARCHAR(64)  NOT NULL COMMENT '节点编码',
  `operator_id`         BIGINT       NOT NULL COMMENT '操作人',
  `operator_role`       VARCHAR(64)  NULL COMMENT '操作人角色',
  `action_comment`      VARCHAR(1000) NULL COMMENT '审批意见',
  `before_rate`         DECIMAL(9,6) NULL COMMENT '动作前利率',
  `after_rate`          DECIMAL(9,6) NULL COMMENT '动作后利率',
  `operation_channel`   VARCHAR(16)  NOT NULL COMMENT 'PC/MOBILE',
  `device_id`           VARCHAR(64)  NULL,
  `operation_time`      DATETIME     NOT NULL,
  `idempotency_key`     VARCHAR(64)  NULL COMMENT '幂等键',
  `from_status`         VARCHAR(32)  NULL COMMENT '动作前状态(状态机轨迹,由审批模块填充)',
  `to_status`           VARCHAR(32)  NULL COMMENT '动作后状态(状态机轨迹,由审批模块填充)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_action_idem` (`idempotency_key`),
  KEY `idx_action_pricing` (`pricing_item_id`),
  KEY `idx_action_operator` (`operator_id`,`operation_time`)
) ENGINE=InnoDB COMMENT='ccr_approval_action 审批业务轨迹';

-- ---------- 附件 ----------
CREATE TABLE IF NOT EXISTS `ccr_attachment` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `biz_type`            VARCHAR(32)  NOT NULL COMMENT 'APPLICATION/RESOLUTION等',
  `biz_id`              BIGINT       NOT NULL COMMENT '业务主键',
  `biz_item_id`         BIGINT       NULL COMMENT '业务子项主键(分项/借据/担保)',
  `file_name`           VARCHAR(200) NOT NULL COMMENT '文件名',
  `file_type`           VARCHAR(32)  NULL COMMENT '文件类型',
  `file_size`           BIGINT       NULL COMMENT '字节数',
  `file_path`           VARCHAR(500) NOT NULL COMMENT '存储路径/对象key',
  `file_hash`           CHAR(64)     NULL COMMENT '文件SHA-256',
  `upload_by`           BIGINT       NOT NULL COMMENT '上传人',
  `upload_time`         DATETIME     NOT NULL COMMENT '上传时间',
  `remark`              VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_attach_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB COMMENT='ccr_attachment 附件(证明材料)';

-- ---------- 审批决议 ----------
CREATE TABLE IF NOT EXISTS `ccr_resolution` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL COMMENT 'ISSUED/EXECUTED/CLOSED',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `resolution_no`       VARCHAR(64)  NOT NULL COMMENT '决议编号(唯一)',
  `pricing_item_id`     BIGINT       NOT NULL COMMENT '定价分项主键(唯一)',
  `pricing_carrier_type` VARCHAR(24) NOT NULL COMMENT 'LOAN_CONTRACT/DEPOSIT_ACCOUNT',
  `pricing_carrier_business_key` VARCHAR(64) NOT NULL COMMENT '执行载体业务标识',
  `final_rate`          DECIMAL(9,6) NOT NULL COMMENT '最终决议利率',
  `effective_from`      DATE         NOT NULL COMMENT '决议生效日',
  `effective_to`        DATE         NOT NULL COMMENT '决议失效日',
  `decision_source`     VARCHAR(32)  NOT NULL COMMENT 'VOTE_APPROVED/PRESIDENT_APPROVED',
  `issue_time`          DATETIME     NOT NULL COMMENT '决议签发时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resolution_no` (`resolution_no`),
  UNIQUE KEY `uk_resolution_pricing_item` (`pricing_item_id`)
) ENGINE=InnoDB COMMENT='ccr_resolution 审批决议(决议不是合同)';

-- ---------- 决议执行与核验 ----------
CREATE TABLE IF NOT EXISTS `ccr_resolution_execution` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL COMMENT 'ISSUED/CONTRACT_PENDING/CONTRACT_BOUND/EXECUTED/RECONCILE_EXCEPTION/CLOSED',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `resolution_id`       BIGINT       NOT NULL COMMENT '决议主键',
  `contract_business_key` VARCHAR(64) NOT NULL COMMENT '合同业务标识',
  `loan_contract_no`    VARCHAR(64)  NULL COMMENT '回填正式合同号',
  `supplement_agreement_no` VARCHAR(64) NULL COMMENT '补充协议编号',
  `execution_rate`      DECIMAL(9,6) NULL COMMENT '合同执行利率',
  `bind_time`           DATETIME     NULL COMMENT '合同绑定时间',
  `execution_status`    VARCHAR(32)  NOT NULL DEFAULT 'ISSUED' COMMENT '执行状态(§12.4):ISSUED/CONTRACT_PENDING/CONTRACT_BOUND/EXECUTED/RECONCILE_EXCEPTION/CLOSED',
  `source_batch_id`     VARCHAR(64)  NULL COMMENT '核验来源数仓批次',
  `reconcile_result`    VARCHAR(32)  NULL COMMENT 'PASS/WARN/FAILED',
  `reconcile_time`      DATETIME     NULL COMMENT '核验时间',
  `difference_json`     JSON         NULL COMMENT '核验差异明细',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_execution` (`resolution_id`,`contract_business_key`),
  KEY `idx_execution_contract` (`loan_contract_no`)
) ENGINE=InnoDB COMMENT='ccr_resolution_execution 决议执行与核验(不覆盖原决议)';

-- ---------- 拟达成贡献度承诺(申请随单录入,审批通过后由承诺模块生成正式计划) ----------
CREATE TABLE IF NOT EXISTS `ccr_application_commitment` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `pricing_item_id`     BIGINT       NULL COMMENT '关联定价分项(可按成员/指标挂靠,可空)',
  `metric_code`         VARCHAR(40)  NOT NULL COMMENT '贡献度指标编码(对应 dw_contribution_metric.metric_code)',
  `target_type`         VARCHAR(20)  NOT NULL COMMENT '目标类型:AVG_BALANCE日均余额/INCOME收入/CONTRIBUTION_AMOUNT折算额',
  `baseline_value`      DECIMAL(20,4) NULL COMMENT '基线值(万元)',
  `target_value`        DECIMAL(20,4) NOT NULL COMMENT '拟达成目标值(万元)',
  `unit`                VARCHAR(16)  NOT NULL DEFAULT 'WAN_YUAN' COMMENT '计量单位',
  `metric_scope`        VARCHAR(15)  NOT NULL COMMENT 'PUBLIC/PRIVATE_SELF/RELATED/GROUP/GROUP_MEMBER',
  `member_customer_no`  VARCHAR(64)  NULL COMMENT '集团成员客户号(集团场景)',
  PRIMARY KEY (`id`),
  KEY `idx_commit_app` (`application_id`),
  KEY `idx_commit_pricing` (`pricing_item_id`)
) ENGINE=InnoDB COMMENT='ccr_application_commitment 拟达成贡献度承诺(§7.1录入;审批通过后生成正式承诺计划)';

-- ---------- 人工补录他行融资(申请随单录入;审批详情展示,提交时绑定快照) ----------
CREATE TABLE IF NOT EXISTS `ccr_application_other_loan` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `lender_name`         VARCHAR(128) NOT NULL COMMENT '他行机构名称',
  `credit_amount`       DECIMAL(20,4) NULL COMMENT '授信额(万元)',
  `used_amount`         DECIMAL(20,4) NULL COMMENT '已用额(万元)',
  `balance_amount`      DECIMAL(20,4) NULL COMMENT '余额(万元)',
  `annual_rate`         DECIMAL(9,6)  NULL COMMENT '年化利率%',
  `input_mode`          VARCHAR(16)  NOT NULL DEFAULT 'MANUAL' COMMENT '录入方式:MANUAL人工/EXCEL导入',
  PRIMARY KEY (`id`),
  KEY `idx_otherloan_app` (`application_id`)
) ENGINE=InnoDB COMMENT='ccr_application_other_loan 人工补录他行融资(§7.1步骤6;与数仓权威快照分离存储)';

-- ---------- 申请附件(材料附件步骤上传,内容落库;审批详情/档案可下载) ----------
CREATE TABLE IF NOT EXISTS `ccr_application_attachment` (
  `id`                  BIGINT       NOT NULL,
  `tenant_id`           VARCHAR(20)  NOT NULL DEFAULT '000000',
  `business_no`         VARCHAR(64)  NOT NULL,
  `org_id`              BIGINT       NOT NULL,
  `status`              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
  `version_no`          INT          NOT NULL DEFAULT 1,
  `create_dept`         BIGINT       NULL,
  `create_by`           BIGINT       NOT NULL,
  `create_time`         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by`           BIGINT       NULL,
  `update_time`         DATETIME     NULL,
  `del_flag`            CHAR(1)      NOT NULL DEFAULT '0',
  `application_id`      BIGINT       NOT NULL COMMENT '申请主键',
  `file_name`           VARCHAR(255) NOT NULL COMMENT '文件名',
  `file_size`           BIGINT       NOT NULL COMMENT '文件大小(字节)',
  `file_type`           VARCHAR(128) NULL COMMENT '内容类型(MIME)',
  `content`             MEDIUMBLOB   NOT NULL COMMENT '文件内容(演示期落库;生产建议对象存储)',
  PRIMARY KEY (`id`),
  KEY `idx_att_app` (`application_id`)
) ENGINE=InnoDB COMMENT='ccr_application_attachment 申请附件(材料附件步骤上传)';
