<template><div class="overlay"><section class="sheet" role="dialog" aria-modal="true" aria-label="审批操作"><div class="sheet-head"><h2>{{review?'确认本次操作':choice==='REJECT'?'否决申请':'同意申请'}}</h2><button aria-label="关闭" :disabled="busy" @click="close">×</button></div><div class="sheet-body">
<p class="body-copy">{{detail.name}}</p><p class="subtext">{{detail.application.applicationNo}}</p>
<div v-if="error" class="error-box" role="alert">{{error}}</div>
<template v-if="!review"><p v-if="task.kind==='vote'" class="notice info">本次提交本人整单票，提交后不可修改。</p><template v-if="editable"><label class="form-label">逐分项审批利率 <small>每次调整 1 BP</small></label><div v-for="item in detail.items" :key="item.id" class="rate-edit"><p>{{item.pricingItemNo}} · {{item.memberName || item.guaranteeType || '定价分项'}}</p><div class="rate-fields"><div><div class="value-caption">调整前</div><div class="numeric">{{rate(item.currentApprovalRate??item.requestedRate)}}</div></div><div><label class="value-caption" :for="'rate-'+item.id">审批后利率（%）</label><div class="rate-stepper"><input :id="'rate-'+item.id" v-model="values[String(item.id)]" type="number" step="0.01" inputmode="decimal"><div class="rate-stepper-buttons"><button aria-label="提高1BP" @click="step(item,1)">＋</button><button aria-label="降低1BP" @click="step(item,-1)">−</button></div></div></div></div></div><p class="subtext">1 BP = 0.01 个百分点。最终审批去向由后台权限矩阵确定。</p></template>
<label class="form-label" for="comment">{{task.kind==='vote'?'表决意见':'审批意见'}} <small>{{choice==='REJECT'?'必填':'选填'}}</small></label><textarea id="comment" v-model="comment" maxlength="500" placeholder="请输入具体意见"></textarea><div class="filters gap" v-if="choice!=='REJECT'"><button class="chip" @click="comment='同意，按审批流程办理。'">同意办理</button><button class="chip" @click="comment='同意，请持续关注承诺履约。'">关注履约</button></div>
</template><template v-else><div class="confirm-result">{{choice==='REJECT'?(task.kind==='vote'?'提交否决票，参与小组计票。':'整笔申请否决，操作不可撤销。'):'确认后提交本节点操作，处理结果以服务器返回为准。'}}</div><div v-for="item in detail.items" :key="item.id" class="data-row"><span>{{item.pricingItemNo}}</span><span>{{rate(item.currentApprovalRate??item.requestedRate)}} → {{rate(editable?values[String(item.id)]:(item.currentApprovalRate??item.requestedRate))}}</span></div><p class="body-copy">{{comment||'未填写意见'}}</p></template>
<div class="sheet-actions"><button class="secondary" :disabled="busy" @click="uncertain?close():review?(review=false):close()">{{uncertain?'返回核对状态':review?'返回修改':'取消'}}</button><button class="primary" :class="{danger:choice==='REJECT'}" :disabled="busy" @click="review?submit():prepare()">{{busy?'提交中…':uncertain?'重试本次请求':review?'确认提交':'核对并继续'}}</button></div></div></section></div></template>
<script setup>
import {ref,computed} from 'vue';import {request,newKey} from '../api.mjs';import {rate,validateRates} from '../data.mjs';
const props=defineProps(['detail','task','choice']);const emit=defineEmits(['close','success']);
const values=ref(Object.fromEntries(props.detail.items.map(i=>[String(i.id),i.currentApprovalRate??i.requestedRate]))),comment=ref(''),error=ref(''),busy=ref(false),review=ref(false),uncertain=ref(false);
const editable=computed(()=>props.choice==='APPROVE'&&props.task.kind==='approval'&&props.detail.loan&&props.task.node!=='SECRETARY');
let command=null;
function step(item,dir){const k=String(item.id),v=Number(values.value[k]);if(Number.isFinite(v)&&v+dir*.01>0&&v+dir*.01<=36)values.value[k]=Math.round((v+dir*.01)*1000000)/1000000;}
function prepare(){try{error.value='';if(props.choice==='REJECT'&&!comment.value.trim())throw Error('请填写否决原因');const adjustments=editable.value?validateRates(props.detail.items,values.value):undefined;const common={applicationId:props.detail.id};let path,body;if(props.task.kind==='vote'){const round=props.task.roundId??props.detail.voteRound?.roundId;if(!round)throw Error('表决轮次已变更，请重新加载');path=`/vote-rounds/${round}/ballots`;body={...common,choice:props.choice,comment:comment.value.trim()};}else if(props.task.kind==='president'){path='/decisions';body={...common,decision:props.choice==='REJECT'?'VETO':'APPROVE',opinion:comment.value.trim()};}else{const version=props.detail.application.versionNo;if(version==null)throw Error('缺少申请版本，请重新加载');path=props.choice==='REJECT'?'/reject':'/approve';body={...common,nodeCode:props.task.node,versionNo:version,comment:comment.value.trim(),rateAdjustments:adjustments};}command={path,body,key:newKey()};review.value=true;}catch(e){error.value=e.message;}}
async function submit(){if(busy.value||!command)return;busy.value=true;error.value='';try{const result=await request(command.path,{method:'POST',body:command.body,key:command.key});emit('success',result);}catch(e){uncertain.value=e.uncertain;error.value=e.message+(e.uncertain?'。结果尚未确认，请使用同一请求重试，或返回重新核对待办。':'');}finally{busy.value=false;}}
function close(){if(!busy.value)emit('close',uncertain.value);}
</script>
