<template><section class="detail-summary"><span class="tag">{{nodeNames[detail.badgeCode]||stateNames[detail.badgeCode]||detail.badgeCode||'—'}}</span><h1>{{detail.name}}</h1><p class="subtext">{{businessNames[detail.application.businessType]||detail.application.businessType}} · {{detail.application.applicantOrgName}}</p><p class="subtext">申请编号 {{detail.application.applicationNo}}</p><div class="summary-metrics"><div><p class="value-caption">申请金额（万元）</p><b class="numeric">{{fmt(detail.items.reduce((n,i)=>n+Number(i.pricingAmount||0),0))}}</b></div><div><p class="value-caption">当前申请利率</p><b class="numeric rate-blue">{{range(detail.items.map(i=>i.currentApprovalRate??i.requestedRate).filter(v=>v!=null))}}</b></div></div></section>
<div class="detail-toolbar" ref="toolbar"><nav class="detail-tabs" role="tablist"><button v-for="[key,label] in tabs" :key="key" role="tab" :aria-selected="tab===key" :class="{active:tab===key}" @click="switchTab(key)">{{label}}</button></nav></div>
<div class="detail-content section-body" ref="panel">
<template v-if="tab==='application'"><div class="notice info">{{detail.source==='SNAPSHOT'?'提交时冻结数据':'当前展示数据未标记为冻结快照'}}<span v-if="detail.snapshotInfo"> · {{date(detail.snapshotInfo.freezeTime)}}</span></div><section class="panel"><h3>分项利率 <small>{{detail.items.length}} 个分项</small></h3><div v-for="(item,index) in detail.items" :key="item.id" class="item-block"><h3><span class="tag">{{String(index+1).padStart(2,'0')}}</span> {{item.pricingItemNo}}</h3><DataRows :value="item" :fields="[['产品编码','productCode'],['申请金额（万元）','pricingAmount'],['期限','termValue'],['期限单位','termUnit'],['合同编号','contractNo'],['成员客户号','memberCustomerNo']]"/><div class="rate-compare"><div><p class="value-caption">原执行利率</p><b class="numeric">{{rate(item.originalRate)}}</b></div><span>›</span><div><p class="value-caption">当前审批利率</p><b class="numeric rate-blue">{{rate(item.currentApprovalRate??item.requestedRate)}}</b></div></div></div></section><section class="panel"><h3>客户与申请信息</h3><DataRows :value="detail.customer" :fields="[['客户名称','customerName'],['客户编号','customerNo'],['信用等级','creditLevel'],['五级分类','fiveLevelClass'],['行业','industry']]"/><section class="application-remark" aria-label="申请备注"><div class="remark-heading"><h4>申请备注</h4><span>申请人填写</span></div><p :class="{'remark-empty':!detail.application.applicationRemark?.trim()}">{{detail.application.applicationRemark?.trim()||'申请人未填写备注'}}</p></section></section><QualityResults :rows="detail.qualityResults"/></template>
<template v-if="tab==='contribution'"><section class="panel"><h3>客户贡献度</h3><div v-for="(row,i) in detail.contribution" :key="i" class="data-row"><span>{{row.metricName||metricName(row.metricCode)}}</span><span>{{fmt(row.metricValue,4)}} <small class="metric-unit">{{contributionUnit(row,isRatioMetric(row.metricCode),isCountMetric(row.metricCode))}}</small></span></div><p v-if="!detail.contribution?.length" class="empty">暂无贡献度数据</p></section><section class="panel"><h3>拟达成承诺</h3><div v-for="(row,i) in detail.commitments" :key="i" class="item-block"><DataRows :value="row" :fields="[['指标','metricName'],['指标编码','metricCode'],['基准值','baselineValue'],['目标值','targetValue'],['单位','unit'],['到期日','endDate'],['说明','commitmentDesc']]"/></div><p v-if="!detail.commitments?.length" class="empty">暂无承诺</p></section></template>
<template v-if="tab==='material'"><section class="panel"><h3>申请材料</h3><button v-for="f in detail.attachments" :key="f.id" class="file-row" @click="$emit('file',f)"><AttachmentIcon :name="f.fileName"/><span class="file-label">{{f.fileName}}<small class="subtext">{{fmt(f.fileSize/1024)}} KB</small></span><span>›</span></button><p v-if="!detail.attachments?.length" class="empty">暂无附件</p></section><section v-for="group in groups" :key="group.key" class="panel material-group"><h3>{{group.name}}<small>{{detail[group.key]?.length||0}} 笔</small></h3><div v-for="(row,i) in detail[group.key]" :key="i" class="item-block"><div class="material-record-title">{{group.record}} {{String(i+1).padStart(2,'0')}}</div><DataRows :value="row" :fields="group.fields"/></div><p v-if="!detail[group.key]?.length" class="empty">暂无数据</p></section></template>
<template v-if="tab==='history'"><section class="panel"><h3>审批记录</h3><div v-for="(row,i) in detail.flowTrace" :key="i" class="item-block"><div class="section-heading"><b>{{nodeNames[row.nodeCode]||row.nodeCode}}</b><span class="tag">{{actionNames[row.actionType]||row.actionType}}</span></div><p class="subtext">{{row.operatorName}} · {{date(row.operationTime)}}</p><p class="body-copy">{{row.actionComment||'未填写意见'}}</p><p v-if="row.beforeRate!=null" class="subtext">{{rate(row.beforeRate)}} → {{rate(row.afterRate)}}</p></div><p v-if="!detail.flowTrace?.length" class="empty">暂无审批记录</p></section><section v-if="detail.voteRound?.myChoice" class="panel"><h3>我的表决</h3><p>{{detail.voteRound.myChoice==='APPROVE'?'同意':'否决'}}</p><p class="subtext">{{detail.voteRound.myComment}}</p></section><section v-if="detail.voteResults?.length" class="panel"><h3>小组表决结果</h3><div v-for="(r,i) in detail.voteResults" :key="i" class="item-block"><p>{{r.result}} · 同意 {{r.approveCount}} / 否决 {{r.rejectCount}}</p><button class="text-link" @click="loadOpinions(r.roundId)">查看匿名意见</button></div><p v-if="opinionError" class="error-box">{{opinionError}}</p><div v-for="(r,i) in opinions" :key="i"><div v-for="(o,j) in r.opinions" :key="j" class="item-block"><p>匿名 {{o.anonymNo}} · {{o.voteChoice==='APPROVE'?'同意':'否决'}}</p><p class="subtext">{{o.voteComment||'未填写意见'}}</p></div></div></section></template>
</div></template>
<script setup>
import {resetDetailScroll} from '../detail-scroll.mjs';
import AttachmentIcon from './AttachmentIcon.vue';
import {contributionUnit} from '../units.mjs';
import QualityResults from './QualityResults.vue';
import {ref,nextTick} from 'vue';import DataRows from './DataRows.vue';import {fmt,rate,range,date} from '../data.mjs';import {request} from '../api.mjs';
import {isRatioMetric,isCountMetric,metricName,NODE_LABELS as nodeNames,APP_STATUS as stateNames,BUSINESS_TYPE as businessNames,ACTION_TEXT as actionNames} from '../../src/utils/dict';
const toolbar=ref(null),panel=ref(null);
async function switchTab(key){if(tab.value===key)return;tab.value=key;await nextTick();resetDetailScroll(panel.value,toolbar.value);}
const props=defineProps(['detail']);defineEmits(['file']);const tab=ref('application'),opinions=ref([]),opinionError=ref('');const tabs=[['application','申请'],['contribution','贡献'],['material','材料'],['history','记录']];
const groups=[{key:'creditAgreements',name:'授信协议',record:'协议',fields:[['协议编号','agreementNo'],['授信金额（万元）','creditAmount'],['已用金额（万元）','usedAmount'],['起始日','startDate'],['到期日','endDate']]},{key:'financing',name:'本行融资',record:'合同',fields:[['合同编号','contractNo'],['合同金额（万元）','contractAmount'],['贷款余额（万元）','loanBalance'],['担保方式','guaranteeType']]},{key:'guarantees',name:'担保信息',record:'担保',fields:[['担保方式','guaranteeType'],['担保金额（万元）','guaranteeAmount'],['措施编号','measureNo']]},{key:'otherLoans',name:'他行融资',record:'融资',fields:[['机构','lenderName'],['授信金额（万元）','creditAmount'],['余额（万元）','balanceAmount'],['年利率（%）','annualRate']]}];
async function loadOpinions(id){opinionError.value='';try{opinions.value=await request(`/vote-rounds/${id}/opinions`);}catch(e){opinionError.value=e.message;}}
</script>
