<template><div class="overlay attachment-overlay" :class="{'reader-fullscreen':fullscreen}"><section class="sheet" role="dialog" aria-modal="true" aria-label="附件预览"><button v-if="fullscreen" class="immersive-close" aria-label="关闭全屏预览" @click="fullscreen=false">×</button><div v-if="!fullscreen" class="sheet-head"><h2>{{fullscreen?'全屏预览':'申请材料'}}</h2><button v-if="url&&type" class="text-link" @click="fullscreen=!fullscreen">{{fullscreen?'退出全屏':'全屏查看'}}</button><button aria-label="关闭附件" @click="$emit('close')">×</button></div><div class="sheet-body"><h3 v-if="!fullscreen" class="body-copy">{{file.fileName}}</h3><p v-if="loading" class="loading">正在读取附件…</p><p v-if="error" class="error-box">{{error}}</p><template v-if="url&&type?.startsWith('image/')"><ImagePreview v-if="fullscreen" :url="url" :name="file.fileName"/><button v-else class="image-thumbnail" aria-label="全屏查看图片" @click="fullscreen=true"><img class="attachment-image" :src="url" :alt="file.fileName"><span>点击全屏查看 · 支持双指缩放</span></button></template><PdfPreview v-else-if="url&&type==='application/pdf'" :key="url+fullscreen" :url="url"/><p v-if="url&&!fullscreen" class="notice info">{{type==='application/pdf'?'如客户端未显示 PDF，请下载后使用文件阅读器打开。':type?'附件来自本申请材料。':'此格式暂不支持内嵌预览，请下载后查看。'}}</p><a v-if="url&&!fullscreen" :href="url" :download="file.fileName" class="file-download">下载附件</a><button v-if="error" class="secondary full-width" @click="load">重新读取</button></div></section></div></template>
<script setup>
import ImagePreview from './ImagePreview.vue';
import {ref,onMounted,onBeforeUnmount} from 'vue';import {request} from '../api.mjs';import {previewType} from '../files.mjs';
import PdfPreview from './PdfPreview.vue';
const props=defineProps(['file','applicationId']);defineEmits(['close']);const fullscreen=ref(false);const url=ref(''),type=ref(null),error=ref(''),loading=ref(false);let controller,epoch=0;
async function load(){const turn=++epoch;controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{const blob=await request(`/applications/${props.applicationId}/attachments/${props.file.id}`,{binary:true,signal:controller.signal});if(blob.size>20*1024*1024)throw Error('附件超过移动端预览上限，请在电脑端查看');const mime=previewType(new Uint8Array(await blob.slice(0,16).arrayBuffer()));if(turn!==epoch)return;if(url.value)URL.revokeObjectURL(url.value);type.value=mime;url.value=URL.createObjectURL(new Blob([blob],{type:mime||'application/octet-stream'}));}catch(e){if(turn===epoch)error.value=e.message;}finally{if(turn===epoch)loading.value=false;}}
onMounted(load);onBeforeUnmount(()=>{epoch++;controller?.abort();if(url.value)URL.revokeObjectURL(url.value);});
</script>
