<template><div class="image-reader free-image-reader"><div ref="box" class="image-viewport free-image-stage" @touchstart="start" @touchmove.prevent="move" @touchend="end" @touchcancel="end" @dblclick="resize(zoom===1?2:1)" @pointerdown="mouseStart" @pointermove="mouseMove" @pointerup="drag=null" @pointercancel="drag=null"><img ref="photo" :src="url" :alt="name" draggable="false" :style="{width:width+'px',height:height+'px',transform:`translate(calc(-50% + ${pan.x}px), calc(-50% + ${pan.y}px)) scale(${zoom})`}" @load="fit" @error="failed=true"/></div><div class="pdf-controls"><button aria-label="缩小图片" :disabled="zoom<=1" @click="resize(zoom-.25)">−</button><button class="pdf-percent" aria-label="恢复图片大小" @click="resize(1)">{{Math.round(zoom*100)}}%</button><button aria-label="放大图片" :disabled="zoom>=5" @click="resize(zoom+.25)">＋</button></div><p v-if="failed" class="error-box">图片读取失败，请下载后查看</p></div></template>
<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue';import {touchDistance} from '../preview-zoom.mjs';import {imageScale,imageZoomAt} from '../free-preview.mjs';
defineProps(['url','name']);const box=ref(null),photo=ref(null),zoom=ref(1),width=ref(1),height=ref(1),pan=ref({x:0,y:0}),failed=ref(false);let gesture,observer;const drag=ref(null);
function fit(){const img=photo.value,el=box.value;if(!img?.naturalWidth||!el)return;const ratio=Math.min(el.clientWidth/img.naturalWidth,el.clientHeight/img.naturalHeight);width.value=img.naturalWidth*ratio;height.value=img.naturalHeight*ratio;}
function resize(value,point={x:0,y:0}){const after=imageScale(value);pan.value=after===1?{x:0,y:0}:imageZoomAt(pan.value,point,zoom.value,after);zoom.value=after;}
function midpoint(t){const r=box.value.getBoundingClientRect();return {x:(t[0].clientX+t[1].clientX)/2-r.left-r.width/2,y:(t[0].clientY+t[1].clientY)/2-r.top-r.height/2};}
function start(e){const t=e.touches;if(t.length>=2)gesture={distance:touchDistance(t),zoom:zoom.value,point:midpoint(t),pan:{...pan.value}};else if(t.length===1)gesture={x:t[0].clientX,y:t[0].clientY,pan:{...pan.value}};}
function move(e){if(!gesture)return;const t=e.touches;if(t.length>=2&&gesture.distance>0){const scale=imageScale(gesture.zoom*touchDistance(t)/gesture.distance),point=midpoint(t),next=imageZoomAt(gesture.pan,gesture.point,gesture.zoom,scale);zoom.value=scale;pan.value={x:next.x+point.x-gesture.point.x,y:next.y+point.y-gesture.point.y};}else if(t.length===1&&gesture.x!=null)pan.value={x:gesture.pan.x+t[0].clientX-gesture.x,y:gesture.pan.y+t[0].clientY-gesture.y};}
function end(e){gesture=null;if(e.touches?.length)start(e);}
function mouseStart(e){if(e.pointerType!=='mouse')return;box.value.setPointerCapture(e.pointerId);drag.value={x:e.clientX,y:e.clientY,pan:{...pan.value}};}
function mouseMove(e){if(!drag.value)return;pan.value={x:drag.value.pan.x+e.clientX-drag.value.x,y:drag.value.pan.y+e.clientY-drag.value.y};}
onMounted(()=>{observer=new ResizeObserver(fit);observer.observe(box.value);});onBeforeUnmount(()=>observer?.disconnect());
</script>
